version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-insurance-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST:    
      POSTGRES_PORT: 5432
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DATABASE: MOTOR_INSURANCE_WEBSITE
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: MOTOR_INSURANCE_WEBSITE
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: